services:
 - docker
before_install:
 - make dbuild
install:
 - make release
env:
  matrix:
    secure: USSp2FISndH8OQKTkLep+fNO4StyN8uJ+dd/QJNU8/Q+GdTKJEnTWXnZphfvXW3JzFpGi8lDStEoy2QAXQoYnngDElKXswapv4qKDIt115GWTqYFdicpSP6k1blGwybOQnMImOEu6nyPBNQGgarVRwB9BR6oxAQxErQSpB3KLibaJB1my6lVreDphdChGeSKf0wIm1BDOiNbk4C18omRIgIWCgxoGmATDthV904a5QTUh75g1qipXppx7pMh+szo3Z935oxYCLLmTSiBwENxCIgITDxbXFFtOJw6xTfM5uGQBZcoPHmeRg4zD9r9BKS+M9YOIp+NK0kqV5ANJOHGdNmTqSgJyPoJwmcZN5z4hBxBdPyIlqB/DRe0v8K71uWwfEI8R0fyU0/6tq+5JC8+VE97gpmQhtXCmD4/yoiQKQ4eASUzQNfzT+XCTgQDsTjGejAc2nQU6981MTUaOlVk1yCmLC7mQi2r5tTs9FgEY8Dof/OzY9MPnOiUytpL0kjyIsO9+L2uH+sdrsttl8Lu2i2bWYy2rL/2wRFSMpkgySac9+wzNFh0OaveYA51la/bPPZTbUOlJW8zErNZWX4zofWNh3HFns3RNiQnbab35s4yZHLsLcA2YbLDU9d3IUoFHsbxZDgbU/GBA1TC9La/zgptrzKebF398cuVqxEs/9Q=
